"""add relations

Revision ID: 42a3c12020de
Revises: 9191256135be
Create Date: 2020-03-26 16:49:03.531116

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42a3c12020de'
down_revision = '9191256135be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.add_column(sa.Column('criteria_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('platform_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('status_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_platform_id', 'platform', ['platform_id'], ['id'])
        batch_op.create_foreign_key('fk_criteria_id', 'criteria', ['criteria_id'], ['id'])
        batch_op.create_foreign_key('fk_status_id', 'status', ['status_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('status_id')
        batch_op.drop_column('platform_id')
        batch_op.drop_column('criteria_id')

    # ### end Alembic commands ###
