"""add platform table

Revision ID: 842569a00afd
Revises: 
Create Date: 2020-03-17 15:33:18.426403

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '842569a00afd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('platform',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('platform')
    # ### end Alembic commands ###
